[package]
name = "forensic-acquisition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_info = { version = "3", default-features = false }
forensic-rs = "0.3.1"
frnsc-liveregistry-rs = "0.1.2"